### ISSUE TITLE
add path parameter?

### ISSUE THREAD

**Issue by titaniumbones** [alessioalex/git-commits#5]
My JS is a little weak so I may be missing a feature that already exists.  Is it possible to pass a path parameter to git-commits, e.g. to replicate a command like

` git rev-list --all -- R some/sub/directory/path`

If it already esitsts, it'd help me out tremendously. If not, I can try to implement it if you're amenable to patches (though the code quality will likely be low!)

Thanks for the package!

**Comment by alessioalex** [comment]
Hey there,

Thank you for opening an issue on this. I think this is already implemented: https://github.com/alessioalex/git-commits/blob/master/index.js#L68 

You just need to set the 'path' option:

```js
gitCommits(repoPath, {
  limit: 2,
 path: 'some/sub/directory/path'
})
```

Let me know if that works for you!

**Comment by titaniumbones** [comment]
ah, I'd just now found it and was fooling around with it. Didn't expect you to be so quick! thank you for the help!

**Comment by alessioalex** [comment]
No problem!

By the way, what are you using the module for?

**Comment by titaniumbones** [comment]
For teaching purposes, to remind students that they need to have a minimum number of commits in their assignments. So for instance,

https://github.com/DigitalHistory/assignment-00-git-and-github/blob/master/test/test.js#L65 

I want to consolidate some of my assignments into a single repo and have separate git tests for each subdirectory; the path option makes that possible, os that's fantastic!

**Comment by alessioalex** [comment]
@titaniumbones that's fantastic to hear! I originally built this for my own project, a Github like server (which I have been using for the last couple of years). I didn't finish the project, but it has a lot of functionality needed to cover anything related to commits / history / blame / source code / authors etc (~Github but without the user collaboration part, essentially a read only version of it that supports pushing as well).

I've open sourced everything git-related: https://github.com/alessioalex?utf8=%E2%9C%93&tab=repositories&q=git&type=source&language=

Let me know if you need any help with this or you need something that's not covered by my modules.

**Comment by alessioalex** [comment]
I forgot to ask: would it be ok to include a link to [DigitalHistory/assignment-00-git-and-github](https://github.com/DigitalHistory/assignment-00-git-and-github) on the repo's readme? It would be nice to have a 'real world use cases' section or something of the sorts.

Thanks

**Comment by titaniumbones** [comment]
:-) especially now that you've cleaned up the code a little bit!  Of course, please feel free. I use it in my other assignments too, but the code quality might be even worse there...

**Comment by alessioalex** [comment]
Sure thing. Let me know if you need any help with your repos / ideas. I'd be glad to help with JavaScript and Node related projects.
